version: 2.1
jobs:
  say-git-version:
    docker:
      - image: cimg/base:current

    steps:
      - checkout
      - run:
          name: "Say git version"
          command: "echo << pipeline.git.revision >>"

workflows:
  say-git-version-workflow:
    jobs:
      - say-git-version